# Generated by Django 4.1 on 2022-12-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                ("name", models.CharField(max_length=30)),
                (
                    "ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("Passwd", models.CharField(max_length=30)),
            ],
        ),
    ]
