# Generated by Django 4.1 on 2022-12-05 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account", old_name="Passwd", new_name="passwd",
        ),
    ]
