# Generated by Django 4.1 on 2022-12-05 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("account", "0002_rename_passwd_account_passwd"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("subject", models.CharField(max_length=30)),
                ("sum", models.IntegerField(default=0)),
                (
                    "pID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.account",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day", models.CharField(max_length=30)),
                ("preiod", models.CharField(max_length=30)),
                ("classroom", models.CharField(max_length=30)),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="submit.lecture"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attendence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(verbose_name="date published")),
                ("attend", models.IntegerField(default=0)),
                (
                    "image",
                    models.ImageField(default="media/default_image.jpg", upload_to=""),
                ),
                (
                    "ID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="submit.lecture"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="class",
            constraint=models.UniqueConstraint(
                fields=("day", "preiod", "ID"), name="Class-unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="attendence",
            constraint=models.UniqueConstraint(
                fields=("date", "ID"), name="Attendence-unique"
            ),
        ),
    ]
