# Generated by Django 4.1 on 2022-12-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submit",
            "0002_remove_class_class-unique_rename_preiod_class_period_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="class", name="period", field=models.IntegerField(default=0),
        ),
    ]
