# Generated by Django 4.1 on 2022-12-05 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0003_alter_class_period"),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="class", name="Class-unique",),
        migrations.RenameField(model_name="class", old_name="ID", new_name="lID",),
    ]
