# Generated by Django 4.1 on 2022-12-05 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0004_remove_class_class-unique_rename_id_class_lid"),
    ]

    operations = [
        migrations.RenameField(model_name="class", old_name="lID", new_name="ID",),
    ]
