# Generated by Django 4.1 on 2022-12-06 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0006_alter_class_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(model_name="attendence", old_name="ID", new_name="lID",),
        migrations.RenameField(model_name="class", old_name="ID", new_name="lID",),
        migrations.CreateModel(
            name="Attendence_Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit", models.BooleanField(default=True)),
                (
                    "aID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="submit.attendence",
                    ),
                ),
                (
                    "sID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="submit.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="attendence",
            name="members",
            field=models.ManyToManyField(
                through="submit.Attendence_Student", to="submit.student"
            ),
        ),
        migrations.AddField(
            model_name="lecture",
            name="members",
            field=models.ManyToManyField(to="submit.student"),
        ),
    ]
