# Generated by Django 4.1 on 2022-12-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "submit",
            "0007_student_rename_id_attendence_lid_rename_id_class_lid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(model_name="attendence", name="Attendence-unique",),
        migrations.AddConstraint(
            model_name="attendence",
            constraint=models.UniqueConstraint(
                fields=("date", "lID"), name="Attendence-unique"
            ),
        ),
    ]
