# Generated by Django 4.1 on 2022-12-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0009_remove_attendence_attendence-unique_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="attendence",
            constraint=models.UniqueConstraint(
                fields=("date", "lID"), name="Attendence-unique"
            ),
        ),
    ]
