# Generated by Django 4.1 on 2022-12-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0010_attendence_attendence-unique"),
    ]

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "ID",
                    models.CharField(max_length=30, primary_key=True, serialize=False),
                ),
                (
                    "image",
                    models.ImageField(default="media/default_image.jpg", upload_to=""),
                ),
            ],
        ),
    ]
