# Generated by Django 4.1 on 2022-12-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submit", "0011_posts"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendence",
            name="image",
            field=models.ImageField(default="media/default_image.jpg", upload_to=""),
        ),
        migrations.AlterField(
            model_name="attendence",
            name="date",
            field=models.CharField(max_length=30),
        ),
    ]
