# Generated by Django 4.1 on 2022-12-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bg_removal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(default="media/default_image.jpg", upload_to=""),
        ),
    ]
