# Generated by Django 4.1 on 2022-12-05 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
        (
            "bg_removal",
            "0003_user_lecture_class_attendence_class_class-unique_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="pID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="account.account"
            ),
        ),
        migrations.DeleteModel(name="User",),
    ]
